sonar.projectKey=buicongthanh861_3-tier-user-platform
sonar.organization=java-woof
sonar.host.url=https://sonarcloud.io

# Quét toàn bộ source code
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/coverage/**,**/dist/**,**/build/**,**/*.test.js

